export const faqCopy = {
  landingTitle: "سوالات متداول",
  landingDescription: "پرسش‌های رایج را بر اساس موضوع ببینید.",
  breadcrumb: "سوالات متداول",
  emptyTitle: "هنوز دسته‌بندی سوالی آماده نیست.",
  emptyDescription:
    "فقط دسته‌هایی که پرسش واقعی دارند نمایش داده می‌شوند. پس از اتصال منبع محتوا این صفحه پر می‌شود.",
  emptyCategoryTitle: "پرسشی در این دسته ثبت نشده است.",
  emptyCategoryDescription: "به فهرست سوالات متداول برگردید.",
  homeCta: "بازگشت به خانه",
  browseCta: "همه سوالات متداول",
  relatedCategoriesHeading: "دسته‌های دیگر",
  serviceCtaLabel: "مشاهده خدمت مرتبط",
  metadataDescription: "پاسخ پرسش‌های رایج کاربران مهندس من.",
  paginationLabel: "صفحه‌بندی پرسش‌ها",
  searchLabel: "جستجو در سوالات متداول",
  searchPlaceholder: "جستجو در سوالات...",
  searchEmptyTitle: "سوالی با این جستجو پیدا نشد.",
  searchEmptyDescription: "عبارت دیگری را امتحان کنید یا سوال خود را بپرسید.",
  matchedQuestionsHeading: "پرسش‌های یافت‌شده",
  askButtonLabel: "سوال شما در لیست نبود؟ بپرسید",
  askDialogTitle: "سوال خود را بپرسید",
  askDialogDescription:
    "سوال شما برای تیم مهندس من ارسال می‌شود و در صورت عمومی بودن به فهرست اضافه خواهد شد.",
  askQuestionLabel: "متن سوال",
  askQuestionPlaceholder: "سوال خود را اینجا بنویسید...",
  askNameLabel: "نام (اختیاری)",
  askMobileLabel: "شماره موبایل (اختیاری)",
  askSubmitLabel: "ارسال سوال",
  askSubmittingLabel: "در حال ارسال…",
  askCancelLabel: "انصراف",
  askCloseLabel: "بستن",
  askSuccessFallback: "سوال شما ثبت شد.",
  askQuestionTooShort: "متن سوال باید حداقل ۱۰ نویسه باشد.",
  askMobileInvalid: "شماره موبایل را به‌صورت 09xxxxxxxxx وارد کنید.",
} as const;
