export const articlesCopy = {
  hubTitle: "مقالات",
  hubDescription: "مطالب خواندنی درباره خدمات ساختمانی و مسیر انتخاب متخصص.",
  hubBreadcrumb: "مقالات",
  categoryBreadcrumb: "دسته‌بندی",
  emptyTitle: "هنوز مقاله‌ای منتشر نشده است.",
  emptyDescription:
    "پس از اتصال منبع محتوا، فهرست مقالات در این صفحه نمایش داده می‌شود.",
  emptyCategoryTitle: "مقاله‌ای در این دسته نیست.",
  emptyCategoryDescription: "دسته‌های دیگر را ببینید یا به خانه برگردید.",
  homeCta: "بازگشت به خانه",
  browseCta: "مشاهده همه مقالات",
  relatedHeading: "مقالات مرتبط",
  relatedDescription: "بر اساس برچسب‌های مشترک و در صورت نیاز همان موضوع.",
  recommendedHeading: "مقالات پیشنهادی",
  recommendedDescription:
    "بر اساس موضوع، برچسب و مقالات منتخب از همین مجموعه انتخاب شده‌اند.",
  tocHeading: "آنچه در این مقاله می‌خوانید",
  categoriesHeading: "دیگر موضوع‌ها",
  faqsHeading: "پرسش‌های مقاله",
  serviceCtaPrefix: "مشاهده خدمت مرتبط",
  metadataDescription: "مقالات مهندس من درباره خدمات ساختمانی.",
  paginationLabel: "صفحه‌بندی مقالات",
  commentsHeading: "نظرها",
  commentsEmptyTitle: "هنوز نظری ثبت نشده است.",
  commentsEmptyDescription: "اولین نظر را شما بنویسید.",
  commentsPaginationLabel: "صفحه‌بندی نظرها",
  commentNameLabel: "نام",
  commentPhoneLabel: "شماره موبایل",
  commentPhoneHint:
    "شماره فقط برای ارسال نظر است و کنار نظر نمایش داده نمی‌شود.",
  commentBodyLabel: "متن نظر",
  commentSubmitLabel: "ارسال نظر",
  commentSuccessTitle: "نظر شما ثبت شد.",
  commentSuccessDescription:
    "نظر شما پس از تأیید نمایش داده می‌شود.",
  commentErrorFallback: "ارسال نظر انجام نشد. دوباره تلاش کنید.",
  readMoreCta: "مطالعه بیشتر",
  featuredLabel: "مقاله منتخب",
  categoryFilterLabel: "فیلتر موضوع مقالات",
  allCategoriesLabel: "همه",
  searchLabel: "جستجو در مقالات",
  searchPlaceholder: "جستجو در مقالات...",
  searchSubmitLabel: "جستجو",
  sortLabel: "مرتب‌سازی مقالات",
  sortNewest: "جدیدترین‌ها",
  sortPopular: "پربازدیدترین‌ها",
  popularHeading: "مقالات پر بازدید",
  popularDescription: "پربازدیدترین مطالب مهندس من.",
  latestHeading: "تازه ترین مقالات",
  searchEmptyTitle: "مقاله‌ای با این جستجو پیدا نشد.",
  searchEmptyDescription: "عبارت دیگری را امتحان کنید یا فیلترها را پاک کنید.",
  clearSearchCta: "پاک کردن جستجو",
  errorTitle: "دریافت مقالات ممکن نشد.",
  errorDescription: "اتصال به سرور برقرار نشد. کمی بعد دوباره تلاش کنید.",
} as const;
