export const knowledgeCopy = {
  landingTitle: "دانش",
  landingDescription: "نکته‌ها و راهنمایی‌های کوتاه بر اساس موضوع خدمت.",
  breadcrumb: "دانش",
  emptyTitle: "هنوز دسته‌بندی دانشی آماده نیست.",
  emptyDescription:
    "فقط دسته‌هایی با نکته واقعی نمایش داده می‌شوند. پس از اتصال منبع محتوا این صفحه پر می‌شود.",
  emptyCategoryTitle: "نکته‌ای در این دسته ثبت نشده است.",
  emptyCategoryDescription: "به فهرست دانش برگردید.",
  homeCta: "بازگشت به خانه",
  browseCta: "همه بخش‌های دانش",
  tipsHeading: "نکته‌ها",
  serviceCtaLabel: "مشاهده خدمت مرتبط",
  metadataDescription: "نکته‌ها و راهنمایی‌های کاربردی مهندس من.",
  paginationLabel: "صفحه‌بندی نکته‌ها",
  searchLabel: "جستجو در دانش",
  searchPlaceholder: "جستجو در نکته‌ها...",
  categorySelectLabel: "فیلتر دسته‌بندی",
  allCategoriesLabel: "همه دسته‌ها",
  searchEmptyTitle: "نتیجه‌ای پیدا نشد.",
  searchEmptyDescription: "عبارت یا دسته دیگری را امتحان کنید.",
  itemsCount: (count: string) => `${count} نکته`,
} as const;
