export const engineerLoginCopy = {
  title: "ورود مهندس",
  description:
    "برای ورود به پنل مهندس، کد ملی و رمز عبور خود را وارد کنید. این مسیر از ورود کاربر عادی جدا است.",
  otpMethod: "ورود با کد یکبار مصرف",
  passwordMethod: "ورود با کد ملی",
  phoneLabel: "شماره موبایل",
  phonePlaceholder: "09xxxxxxxxx",
  requestOtpLabel: "دریافت کد تأیید",
  otpLabel: "کد تأیید",
  otpHelp: "کد شش‌رقمی ارسال‌شده را وارد کنید.",
  verifyLabel: "ورود",
  passwordLabel: "رمز عبور",
  passwordPlaceholder: "رمز عبور",
  showPassword: "نمایش رمز عبور",
  hidePassword: "پنهان کردن رمز عبور",
  submitPassword: "ورود",
  resendLabel: "ارسال مجدد کد",
  editPhoneLabel: "ویرایش شماره موبایل",
  registerPrefix: "هنوز حساب مهندس ندارید؟",
  registerAction: "ثبت‌نام متخصص",
  mockModeHint: "حالت آزمایشی — پیامک واقعی ارسال نمی‌شود.",
} as const;
